### PR TITLE
Source map 0 7 x

### PR DESCRIPTION
**Pull request by akkumar**
Upgrade source-map to 0.7.x as needed by downstream projects

### CODE REVIEW

**Comment by akkumar** [comment]
@xzyfer - FYI . amended commit here without package-lock.json . Let me know how it looks though. 

important: this does break backward compatibility with node.js pre-6 . FYI . Let me know if that would be ok though.

**Comment by xzyfer** [comment]
We would need to bump the major to merge this. Can you please elaborate on
what issues the current version is causing for people?

On 24 Feb. 2018 3:02 pm, "Karthik K" <notifications@github.com> wrote:

@xzyfer <https://github.com/xzyfer> - FYI . amended commit here without
package-lock.json . Let me know how it looks though.

important: this does break backward compatibility with node.js pre-6 . FYI
. Let me know if that would be ok though.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/sasstools/scss-tokenizer/pull/16#issuecomment-368197693>,
or mute the thread

**Comment by akkumar** [comment]
Since source-map 0.6.0+ , the typings are distributed (.d.ts) within source-map package . Previously a separate  types/source-map is explicitly necessary that has been deprecated since (after source-map 0.6.0 that is). 

FYI more here on - https://github.com/angular/devkit/pull/452 - the bazel build had to be upgraded to depend on source-map 0.7.x .

**Comment by akkumar** [comment]
If we want to bump to a major version, do we need a separate branch for 2.x to continue with fixes , while this can go to master for the major version ?

**Comment by akkumar** [comment]
@xzyfer - major version bumped up given the nature of the changes involving deprecating node<6.

**Comment by akkumar** [comment]
@xzyfer  - what would you suggest to take this one up - a separate branch ?

**Pull request merged**
